// src/mockData/initialData.ts
import { Client, Project, Task, TimeLog, Invoice } from '../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    userId: 'user-default',
    name: 'Sarah Jenkins',
    email: 'sarah@acmestudio.design',
    phone: '+1 (555) 234-8901',
    company: 'Acme Design Studio',
    currency: 'USD',
    hourlyRate: 95,
    paymentTermsDays: 14,
    notes: 'Key client for brand design and web engineering. Invoices sent bi-weekly.',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-2',
    userId: 'user-default',
    name: 'David Sterling',
    email: 'david@fintechlabs.io',
    phone: '+1 (555) 456-7890',
    company: 'FinTech Labs Inc.',
    currency: 'USD',
    hourlyRate: 110,
    paymentTermsDays: 30,
    notes: 'Mobile app development for investment platform.',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client-3',
    userId: 'user-default',
    name: 'Elena Rostova',
    email: 'elena@nordicstyle.co',
    company: 'Nordic Style Living',
    currency: 'EUR',
    hourlyRate: 85,
    paymentTermsDays: 15,
    notes: 'Shopify Plus theme revamp & custom app integration.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    userId: 'user-default',
    clientId: 'client-1',
    name: 'Brand Identity & Web Portal',
    description: 'Complete brand overhaul and Next.js portal development.',
    billingType: 'hourly',
    rate: 95,
    budgetHours: 60,
    budgetAmount: 5700,
    deadline: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
    status: 'active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    userId: 'user-default',
    clientId: 'client-2',
    name: 'Mobile Crypto Wallet MVP',
    description: 'React Native cross-platform MVP with biometric auth & chart widgets.',
    billingType: 'fixed_fee',
    rate: 95, // standard team hourly cost for profit margin calculation
    contractTotal: 8500,
    milestones: [
      {
        id: 'ms-1',
        title: '50% Project Kickoff Deposit',
        amount: 4250,
        percentage: 50,
        dueDate: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
        status: 'paid',
        invoiceId: 'inv-1',
      },
      {
        id: 'ms-2',
        title: 'Beta Release & Biometric Flow',
        amount: 2550,
        percentage: 30,
        dueDate: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
        status: 'pending',
      },
      {
        id: 'ms-3',
        title: 'Final Delivery & App Store Launch',
        amount: 1700,
        percentage: 20,
        dueDate: new Date(Date.now() + 25 * 86400000).toISOString().split('T')[0],
        status: 'pending',
      },
    ],
    budgetHours: 80,
    deadline: new Date(Date.now() + 25 * 86400000).toISOString().split('T')[0],
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    userId: 'user-default',
    clientId: 'client-3',
    name: 'E-commerce Checkout Migration',
    description: 'Ongoing headless Shopify Plus maintenance and 1-click checkout optimization.',
    billingType: 'retainer',
    rate: 85,
    retainerMonthlyFee: 2500,
    retainerHoursCap: 25,
    retainerOvertimeRate: 110,
    budgetHours: 25,
    deadline: new Date(Date.now() + 20 * 86400000).toISOString().split('T')[0],
    status: 'active',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    userId: 'user-default',
    projectId: 'proj-1',
    title: 'Design Component Library in Figma',
    description: 'Buttons, modals, typography tokens, and responsive header.',
    status: 'done',
    priority: 'high',
    estimatedHours: 12,
    orderIndex: 0,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    userId: 'user-default',
    projectId: 'proj-1',
    title: 'Implement Interactive Client Dashboard',
    description: 'Connect Next.js client pages to backend GraphQL endpoints.',
    status: 'in_progress',
    priority: 'urgent',
    estimatedHours: 16,
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    orderIndex: 1,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    userId: 'user-default',
    projectId: 'proj-2',
    title: 'Setup Biometric Auth & Secure Keystore',
    description: 'FaceID / TouchID keychain storage for crypto private keys.',
    status: 'in_progress',
    priority: 'high',
    estimatedHours: 10,
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    orderIndex: 0,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TIMELOGS: TimeLog[] = [
  {
    id: 'log-1',
    userId: 'user-default',
    clientId: 'client-1',
    projectId: 'proj-1',
    taskId: 'task-1',
    description: 'Polishing typography system and design tokens',
    startTime: new Date(Date.now() - 86400000 * 2 - 3600000 * 3).toISOString(),
    endTime: new Date(Date.now() - 86400000 * 2).toISOString(),
    durationSeconds: 10800, // 3 hours
    isBillable: true,
    hourlyRate: 95,
    isInvoiced: true,
    invoiceId: 'inv-sample-1',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'log-2',
    userId: 'user-default',
    clientId: 'client-1',
    projectId: 'proj-1',
    taskId: 'task-2',
    description: 'Built customer summary cards and reactive charts',
    startTime: new Date(Date.now() - 86400000 - 3600000 * 2.5).toISOString(),
    endTime: new Date(Date.now() - 86400000).toISOString(),
    durationSeconds: 9000, // 2.5 hours
    isBillable: true,
    hourlyRate: 95,
    isInvoiced: false, // Unbilled!
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'log-3',
    userId: 'user-default',
    clientId: 'client-2',
    projectId: 'proj-2',
    taskId: 'task-3',
    description: 'Research Expo LocalAuthentication API & iOS keybindings',
    startTime: new Date(Date.now() - 3600000 * 4).toISOString(),
    endTime: new Date(Date.now() - 3600000 * 2).toISOString(),
    durationSeconds: 7200, // 2 hours
    isBillable: true,
    hourlyRate: 110,
    isInvoiced: false, // Unbilled!
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    userId: 'user-default',
    clientId: 'client-2',
    clientName: 'David Sterling',
    clientCompany: 'FinTech Labs Inc.',
    clientEmail: 'david@fintechlabs.io',
    invoiceNumber: 'INV-2026-001',
    issueDate: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    status: 'paid',
    items: [
      {
        id: 'item-1',
        type: 'milestone',
        description: 'Mobile Crypto Wallet MVP - 50% Project Kickoff Deposit',
        quantity: 1,
        unitPrice: 4250,
        amount: 4250,
        milestoneId: 'ms-1',
        projectId: 'proj-2',
      },
    ],
    subtotal: 4250,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 4250,
    currency: 'USD',
    paymentTermsDays: 14,
    notes: 'Direct wire transfer received. Thank you for your partnership!',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    userId: 'user-default',
    clientId: 'client-1',
    clientName: 'Sarah Jenkins',
    clientCompany: 'Acme Design Studio',
    clientEmail: 'sarah@acmestudio.design',
    invoiceNumber: 'INV-2026-002',
    issueDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 9 * 86400000).toISOString().split('T')[0],
    status: 'sent',
    items: [
      {
        id: 'item-2',
        type: 'hourly_log',
        description: 'Brand portal design tokens & component architecture',
        quantity: 12,
        unitPrice: 95,
        amount: 1140,
        projectId: 'proj-1',
      },
    ],
    subtotal: 1140,
    taxRate: 10,
    taxAmount: 114,
    totalAmount: 1254,
    currency: 'USD',
    paymentTermsDays: 14,
    notes: 'Please remit payment via Stripe or direct bank transfer within 14 days.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

